### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by shawnholt** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#10]
This looks like a great approach to payment gateways, but I see that there are efforts for 4.7 to address payments too.  Eileen - what are your thoughts on the future of this integration/support vs future native?  Do you see this has a stopgap measure or strong potential for future civicrm/payment gateway support?  Don't want to adopt if not long-term viable. 

thanks!

**Comment by eileenmcnaughton** [comment]
We have been looking at this as an integral path of the future path - with the extension potentially shipping with core at some point

**Comment by shawnholt** [comment]
I see activity here - appreciate any update on shipping with core or new release?

**Comment by eileenmcnaughton** [comment]
I'm not in a hurry to ship with core as it ties the timeframe to core - but I have been moving some functionality into core. Most of the recent activity has been to support 4.7 & also support new processors. Generally each additional processor takes some work (often changes to the upstream processor repo)

**Comment by eileenmcnaughton** [comment]
I think this will continue to be an extension rather than part of core for the forseeable future. That does not downgrade it & the intention is to move the existing ones OUT of core
