### ISSUE TITLE
Translations in transifex not up to date

### ISSUE THREAD

**Issue by kewljuice** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#113]
I can't find translations for items below in transifex.
- "Your payment was not successful. Please try again"
- "The transaction was not processed. The message from the bank was : %1. Please try again"

Is there a way to update these?

![transifex](https://user-images.githubusercontent.com/3306776/55094568-ea7f6c00-50b6-11e9-8852-ff247177e788.png)

**Comment by kewljuice** [comment]
Shouldn't there be a domain added to each ts function?

```$userMsg = ts('Your payment was not successful. Please try again', array('domain' => 'nz.co.fuzion.omnipaymultiprocessor'));```

**Comment by mattwire** [comment]
The "correct" way to do this now is to use the helper function `E::ts()` for all extension translations.

**Comment by kewljuice** [comment]
I see the ```E::ts()``` is used correctly in the codebase, but how can we update the sentences in transifex, so all the strings are available for translation?

**Comment by mattwire** [comment]
@mlutfy What needs to happen to update translations on extensions?

**Comment by mlutfy** [comment]
It normally updates 24h after a new release.

There seems a problem with the extraction:

https://test.civicrm.org/view/i18n/job/CiviCRM-l10n-mo-build-extensions/139/consoleFull

```
* Processing tag: 3.1 ...
Previous HEAD position was 21f6a8fa Bump version
HEAD is now at 3ec9cd76 Add new version with paypal checkout, requires 5.13
 * Building omnipaymultiprocessor.pot
[warn] first argument of ts() call is no string. (./CRM/Core/Payment/OmnipayMultiProcessor.php:935)
[warn] first argument of ts() call is no string. (./CRM/Core/Payment/PaymentExtended.php:377)
[warn] first argument of ts() call is no string. (./api/v3/Job/ProcessRecurring.php:44)
[warn] first argument of ts() call is no string. (./omnipaymultiprocessor.civix.php:31)


                                           
  [PhpParser\Error]                        
  Syntax error, unexpected '?' on line 33  
                                           
civistrings [-a|--append] [-b|--base="..."] [--header="..."] [--msgctxt="..."] [-o|--out="..."] [files1] ... [filesN]


 * All done
tx INFO: Pushing resource civicrm_extensions.omnipaymultiprocessor
```

I tried running manually:

```
$ civistrings . --verbose
[... not related..]
                                                  
  [PhpParser\Error]                                                  
  Syntax error, unexpected T_CONST, expecting T_FUNCTION on line 27  
                                                                     
Exception trace:
 () at /home/bgm/repositories/civistrings/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:275
 PhpParser\ParserAbstract->parse() at /home/bgm/repositories/civistrings/src/Parser/PhpTreeParser.php:28
 Civi\Strings\Parser\PhpTreeParser->parse() at /home/bgm/repositories/civistrings/src/Command/ExtractCommand.php:154
 Civi\Strings\Command\ExtractCommand->extractFile() at /home/bgm/repositories/civistrings/src/Command/ExtractCommand.php:86
 Civi\Strings\Command\ExtractCommand->execute() at /home/bgm/repositories/civistrings/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /home/bgm/repositories/civistrings/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/bgm/repositories/civistrings/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/bgm/repositories/civistrings/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/bgm/repositories/civistrings/src/Application.php:25
 Civi\Strings\Application::main() at /home/bgm/repositories/civistrings/bin/civistrings:21

civistrings [-a|--append] [-b|--base="..."] [--header="..."] [--msgctxt="..."] [-o|--out="..."] [files1] ... [filesN]
```

I debugged with the following:

```
find ./ -name '*php' -print -exec civistrings {} \;
```

and that led me to php files in the `vendor` directory, some of which are pretty obvious, ex: `./vendor/sebastian/diff/tests/ParserTest.php`.

@totten Any thoughts what would be the best way to tell `civistrings` to ignore `vendor` (and `node_modules`).

Personally, I think we shouldn't bundle dependencies in git.. but that's obviously a big change for this extension, and our release infra is not yet ready (I do it for some of my extensions, but it means manually generating zip files with the full build).

**Comment by mlutfy** [comment]
The fix by @seamuslee001 has finally been merged, so hopefully soon we can get this resolved (still need to build the new civistrings and update it on the build server).

**Comment by mlutfy** [comment]
This is finally fixed. There happened to be another issue with the extension directory that was specifically impacting omnipay (a fork was also published, with the same key, but not available for automatic distribution).

![Capture d’écran de 2020-10-23 13-30-29](https://user-images.githubusercontent.com/254741/97035264-159c9c80-1534-11eb-8750-d3324d4b7e26.png)

(example translation is mine, feel free to change it)

@eileenmcnaughton I think we can close this issue.
