### ISSUE TITLE
Symfony polyfill missing?

### ISSUE THREAD

**Issue by JKingsnorth** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#12]
Hi, when I try to install the extension I receive a require error for vendor/symfony/polyfill-php54/bootstrap.php

The polyfill-php54 library seems to be missing entirely from this GIT repo, and isn't mentioned in the composer.json file either?

**Comment by magnolia61** [comment]
I get kind of like the same error with the latest commits (current master). I know this whole extension and especially the mastercode is unsupported. Just wanted to help you out with this info :-)
Fatal error: require(): Failed opening required '/home/xyz/domains/ourdomain/public_html/sites/all/modules/civicrm_extensions/nz.co.fuzion.omnipaymultiprocessor/vendor/symfony/polyfill-php54/bootstrap.php' (...) in /home/ws/domains/wereldsupporter.nl/public_html/sites/all/modules/civicrm_extensions/nz.co.fuzion.omnipaymultiprocessor/vendor/composer/autoload_real.php on line 58

**Comment by eileenmcnaughton** [comment]
I'll have to rerun composer & check it all gets pulled in I guess

**Comment by JohnFF** [comment]
Added that in a new PR.

**Comment by eileenmcnaughton** [comment]
Thanks both - @JohnFF  has done the composer fix - appreciate it!
