### ISSUE TITLE
Crash on viewing page: "Could not find valid value for key"

### ISSUE THREAD

**Issue by JohnFF** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#14]
With a paypal processor set up, when I go to the page /civicrm/payment/details I get the following error message:

"Sorry but we are not able to provide this at the moment.
Could not find valid value for key"

It appears to go away when this line (#21 CRM/Core/Page/PaymentPage.php) and everything dependent on it is commented out:
$formData = $this->getTransparentRedirectFormData(CRM_Utils_Request::retrieve('key', 'String', CRM_Core_DAO::$_nullObject, TRUE));

Unfortunately that stops the page from working!

**Comment by eileenmcnaughton** [comment]
Are you working with an off-site POST flow? Otherwise you wouldn't expect to see that page
