### ISSUE TITLE
mollie test-payment fails with php warning

### ISSUE THREAD

**Issue by rdozijn** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#141]
I am using civicrm 5.18.3. with wordpress. I am trying to get mollie payments working. The version of the omnipay plugin is 

> Omnipay multiprocessor support (nz.co.fuzion.omnipaymultiprocessor) version 3.8

When I register for an event and do a test payment (I checked 'paid' in the list of statuses) I get a screen that is white and contains the message

> Warning: Class __PHP_Incomplete_Class has no unserializer in /home/myuser/public_html/civicrm-nw/wp-content/plugins/civicrm/civicrm.php on line 361
> 
> Warning: session_start(): Failed to decode session object. Session has been destroyed in /home/myuser/public_html/civicrm-nw/wp-content/plugins/civicrm/civicrm.php on line 361

No mail is received and no registration appears in the dashboard. Also no thankyou screen is showed.

When I register for the event and do a real payment I get the white screen without the warning, a mail is received and the registration appears in the dashboard, but again no thankyou/confirmation screen.

The url of the white screen is 

> https://mysite.nl/civicrm/?page=CiviCRM&q=civicrm%2Fpayment%2Fipn%2F100%2F4

...which looks like the result of getNotifyUrl().
Is it normal the payment process stops here? Is this a configuration issue at my side or is this not the expected behaviour?

I would gladly provide more information if that helps understanding what is going on.

**Comment by eileenmcnaughton** [comment]
@magnolia61 you use Mollie - are you able to shed any light here

**Comment by magnolia61** [comment]
Glad to get in touch, will do

**Comment by rdozijn** [comment]
I just found out that test payments _do_ result in a confirmation email (they were in the spam folder :( ), but still no registration record is created. In older versions, they did show up in the dashboard (recent registrations), so that is why I assume it is to expect. But maybe this is normal behaviour in the meantime.
In any case, the mentioned white screen is showed. And exactly that is what bothers us. I can imagine this is too little information for you, or are you able to reproduce this behaviour? Do you need more info?

**Comment by rdozijn** [comment]
I just upgraded civicrm to 15.9.3. The behaviour is not changed:
after doing a (test) payment with status paid, I get a whit screen with the url ending with `civicrm/?page=CiviCRM&q=civicrm%2Fpayment%2Fipn%2F107%2F4` . I have not yet received the confirmation email, but that can be a bit delayed with test payments.
I know I am very close to being able to use the mollie payment module in my site. I hope you can shine some light on this last obstacle.

**Comment by magnolia61** [comment]
Hello Ruud, we've got Mollie working with omnipay out of the box at the moment. Please find me on chat.civicrm.org to get in touch. My username is magnolia61 over there.

**Comment by rdozijn** [comment]
It looks like a misconfiguration in the mollie parameters. Most probably not a civicrm issue.
