### ISSUE TITLE
Fail upon upgrade using GUI

### ISSUE THREAD

**Issue by themak1985** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#142]
![omnipay issue](https://user-images.githubusercontent.com/28904266/69278077-8f533a00-0baf-11ea-95c3-1faf77efe7ea.png)

Tried upgrading using UI - restored back to 3.7 - things are working now.

**Comment by eileenmcnaughton** [comment]
Hmm - the issue is the name of the folder is incorrect - the 3.7 should not be on the end of it - is that part of the name of your 3.7 dir - you need to rename it - it might take a battle with the caches to handle the renaming - perhaps disable & then rename & re-enable

**Comment by eileenmcnaughton** [comment]
(ie do that before trying to upgrade again)

**Comment by themak1985** [comment]
Disabled extension, renamed, cleared cache, enabled. all was fine - ran update again via UI - same issue. 

![fail again](https://user-images.githubusercontent.com/28904266/69385961-162b1400-0c8f-11ea-88e2-2d4ea193cc96.png)

To manually update - would I disable the extension, replace files with new one, then enable again? Like I do with other extensions, or is there something else to consider?

**Comment by eileenmcnaughton** [comment]
That sounds correct. Maybe make sure you fully remove the old one rather than copying over the top

**Comment by themak1985** [comment]
Done - thanks Eileen.
