### ISSUE TITLE
IPN issues with WordPress

### ISSUE THREAD

**Issue by aiden-grau** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#150]
I use omnipaymultiprocessor with a custom plugin and it works fine in Drupal, testing it out now on a WordPress site and cannot get the IPN to complete a payment. When I simulate the IPN request it works, but it seems as though the IPN from the gateway isn't coming through at all.
Is there something that needs to be done on WordPress to allow it? I notice the WordPress notify url is an admin route...
If you're reading this Eileen I've seen posts of yours about the url encoding etc. but I understand those issues were fixed.

I have almost no WordPress experience, any help would be appreciated!

**Comment by aiden-grau** [comment]
Adding a TRUE to the arguments sent to the url function in getNotifyUrl in PaymentExtended.php solves the problem as it makes sure the IPN URL isn't an admin route.

**Comment by eileenmcnaughton** [comment]
dang - thanks - can you do a PR?

**Comment by eileenmcnaughton** [comment]
(I guess it's related to recent url regressions in core)

**Comment by aiden-grau** [comment]
Eileen I'm sure I saw something you posted a while back where you gave an example of a WordPress IPN url and it was an admin route? It wasn't mentioned as an issue at the time, was that okay at a stage?

**Comment by eileenmcnaughton** [comment]
Thanks - I just merged the PR
