### ISSUE TITLE
Cybersource Required Fields Ignored and some questions

### ISSUE THREAD

**Issue by themak1985** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#154]
Hello - we are using the lovely cybersource payment processor with this plugin and had a few questions.

- We have been having issues where periodically the first and last name fields are not always submitting to cybersource for some reason. Not sure if its a user error but its happening often enough to confuse us.

- While investigating, we realized we can leave all payment fields blank and still submit a payment even though there are required asterix on fields. 

- Cybersource asked us to see if this plugin would work with Cybersource Secure Acceptance Web/Mobile or if its limited to Secure Acceptance Silent Order Pay.

Thank you!

**Comment by eileenmcnaughton** [comment]
This should address the validation issue

https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/1997e883be3d5b99eed672c6cf1f2b57655d6f15

**Comment by eileenmcnaughton** [comment]
Fix in 3.11
