### ISSUE TITLE
Paypal Checkout Page Issues

### ISSUE THREAD

**Issue by mwestergaard** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#165]
Contribution pages with Paypal Checkout have stopped working for me. I noticed that the Total Amount isn't updating and the Payment Options doesn't show. I also use the Extra Fee extension and it doesn't appear. I get a bunch of javascript errors in the console.

![image](https://user-images.githubusercontent.com/38840269/89750364-87f6f800-da80-11ea-9f9b-50473242f06d.png)

If I hit the Contribute button, the page refreshes, fills in the Total Amount, offers the Extra Fee option, and then lets me select a payment method (no js errors).

![image](https://user-images.githubusercontent.com/38840269/89750393-9fce7c00-da80-11ea-8fcb-ac6b8c7a3159.png)

If I then select PayPal Checkout and hit the Paypal button, I get an error: "Site is not correctly configured to process payments".

I am at CiviCRM 5.28.0, Omnipay 3.11, and Extra Fee 1.2. I tried disabling Extra Fee on the payment processor to see if it was contributing to the problem, but it didn't make a difference.

**Comment by eileenmcnaughton** [comment]
@mwestergaard was it working for you previously on different versions?

**Comment by eileenmcnaughton** [comment]
@mwestergaard I just tested & hit the same issue - reverting https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/999a7e5e335d65392acac1b901f8cb855d0ae234 got me past it - are you able to test master?

**Comment by eileenmcnaughton** [comment]
@mwestergaard I've published 3.12 with that reverted - per comments here - https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/164 I have a hunch it could be caching but will re-add that more cautiously if it turns out to be the case

**Comment by mattwire** [comment]
@eileenmcnaughton @mwestergaard Please see/test #166 which should resolve both issues.

**Comment by mwestergaard** [comment]
Thanks. I installed 3.12 but still same behavior. I verified I have the new omnipay_PaypalRest.js, flushed CiviCRM cache, cleared browser cache, etc. I'll keep trying!

**Comment by eileenmcnaughton** [comment]
@mwestergaard did this work for you previously? Does anything start to load. I  got an error before doing the mentioned revert but then I got an error a bit later in the process afterwards (because I had test credentials & tried it in live mode). Also maybe try the patch above

**Comment by mwestergaard** [comment]
@eileenmcnaughton Yes, my contribution pages and payment processor haven't been altered since we started using the Omnipay extension about a year ago, but I believe I found a clue. I had a vague memory of a similar issue occurring in the past. I had to scratch my brain, but I remembered reporting it (https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/issues/126#issuecomment-531587341). I found that if I switch my default Payment Processor to something other than PayPal Checkout, everything seems to work with PayPal Checkout and https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/166. I see no js errors.

The only thing is see different is the Contribute button is hanging around until the Paypal Checkout buttons appear. I'm pretty sure it wasn't displaying at all unless I selected Pay Later (my only other payment option). Perhaps I'm hallucinating!

**Comment by eileenmcnaughton** [comment]
@mwestergaard can you try reverting this - https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/164/commits/b9d5719d026b0de67c0096c7ed9cc8e2e9082931 - I tested with paypal checkout as non-default so that could explain why it worked for me

**Comment by mwestergaard** [comment]
@eileenmcnaughton That was successful! Tested on two systems with results as expected. I reset PayPal Checkout as the default payment processor (and cleared Civi's cache). Everything behaved and completed a couple of test payments.

Ignore my comment about the Contribute button. There was no default payment option on the form at that point, so it makes sense.

**Comment by eileenmcnaughton** [comment]
@mwestergaard OK - I've reverted that too - I'll release 3.13 without those 2 fixes & then when I have time sit down & try to work through @mattwire's proposed alternate

**Comment by mwestergaard** [comment]
@eileenmcnaughton Thanks much!

**Comment by eileenmcnaughton** [comment]
@mwestergaard thanks for reporting it quickly- I still need to revisit re-fixing but at least the regression won't hit others
