### ISSUE TITLE
Thank You / Fail Screen not loading - User gets blank screen.

### ISSUE THREAD

**Issue by themak1985** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#172]
This is strange. Some donors are donating successfully but getting a blank thank you page. The donation is processed, they get an email confirming their donation, but nothing appears on screen. D7 CiviCRM 5.31, Omnipay Cybersource

I can't seem to find any issues in the log either.

The URL at the blank screen is /civicrm/payment/ipn/1

When it works correctly, the thank you screen has a url of civicrm/contribute/transact?_qf_ThankYou_display=1&qfKey=**********************

Even failed transactions are getting a blank white screen. 

Any ideas?

**Comment by eileenmcnaughton** [comment]
@themak1985 2 possibilities
1) they are not being redirected due to the page not being in session or
2) there is a php error - the second should leave errors in your apache log if it is the case

**Comment by Stoob** [comment]
@eileenmcnaughton there may be something else at play such as a browser, cookie or SSL issue.  I can confirm the issue can be consistently reproduced using the Chrome browser on Windows.  Firefox and Safari the issue doesn't occur.  Apache logs are attached.  There are no PHP errors in the log that that I can tell.  Chrome console shows no errors.  CiviCRM.xxxxx.log shows the same log entries whether the 'white screen' shows up or not.
[logfiles_apache.txt](https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/files/5625837/logfiles_apache.txt)
![chrome](https://user-images.githubusercontent.com/1683473/100804108-236df900-33e1-11eb-8604-bc343d3fa3cc.png)

**Comment by eileenmcnaughton** [comment]
@Stoob OK - if it's chrome browser only it's likely the problem we fixed for wordpress but didn't get much drupal traction on - https://lab.civicrm.org/dev/core/-/issues/2059 -

**Comment by Stoob** [comment]
Paypal Standard issue affects Cybersource Omnipay?

**Comment by eileenmcnaughton** [comment]
@Stoob yes because the issue is chrome security on  returning ipns

**Comment by Stoob** [comment]
@eileenmcnaughton ok thanks.  What can we do to help and/or debugging or fix?

**Comment by eileenmcnaughton** [comment]
@Stoob I failed to get much on it - but JonG had a hacky fix - maybe you can connect with him?

**Comment by themak1985** [comment]
This was related to the Chrome IPN Issue - I detailed how we solved it at https://civicrm.stackexchange.com/questions/38247/random-occurrences-of-blank-contribution-thank-you-pages/38352#38352

**Comment by eileenmcnaughton** [comment]
Thanks for the feedback @themak1985 !
