### ISSUE TITLE
4.6 Unable to select province/state on front-end contribution form

### ISSUE THREAD

**Issue by adixon** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#18]
On the front end contribution form, on the billing fields you can't select a province/state. i.e. when you select a country, you're not given any allowed provinces. I have US/Canada provinces enabled, and it works on the profile earlier in the form. Looks like the implementation of the province/country fields for the billing fields is somehow broken. No js errors in the console. The look of the country field is subtly different when I choose a functioning auth.net payment processor.

I'm going to guess this isn't a priority, so I'll see if I can upgrade my install to 4.7.

Leaving this here in case someone else has a similar issue, or if you have an easy fix idea.

**Comment by eileenmcnaughton** [comment]
closing this unless it gets confirmed on 4.7 as 4.6 is not supported
