### ISSUE TITLE
symfony conflicts with D9

### ISSUE THREAD

**Issue by stesi561** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#225]
We've hit some issues with Webform email handlers in some circumstances where Drupal Webform attempts for some reason to use symfony versions included in this extensions vendor directory.
Errors occur when there is function mismatches!

Specifically in 
symfony/mime

which D9.3.9 core recommended requires at 5.4.0

I've managed to work around this by pining the version to that included with drupal via the extension composer.json and then "upgrading" to get the required version however I don't think this is optimal!

When this issue was hit for the CiviCRM d8 project the solution was to install CiviCRM using composer - not sure if that is a viable route for CiviCRM extensions - although it would be nice to have both Drupal Modules and extensions in the same composer.json file!

**Comment by stesi561** [comment]
After resolving mime I see the following differences between composer show on Drupal 9 vs Omnipay

`doctrine/instantiator  D version: 1.4.1, O version: 1.5.x-dev,
myclabs/deep-copy  D version: 1.11.0, O version: 1.x-dev,
phar-io/manifest  D version: 2.0.3, O version: 1.0.1,
phar-io/version  D version: 3.2.1, O version: 1.0.1,
php-http/discovery  D version: 1.14.1, O version: 1.14.0,
php-http/guzzle6-adapter  D version: v2.0.2, O version: dev-master,
php-http/httplug  D version: 2.2.0, O version: dev-master,
php-http/message  D version: 1.12.0, O version: 1.11.1,
php-http/message-factory  D version: v1.0.2, O version: dev-master,
php-http/promise  D version: 1.1.0, O version: dev-master,
phpdocumentor/reflection-common  D version: 2.2.0, O version: dev-master,
phpdocumentor/reflection-docblock  D version: 5.3.0, O version: dev-master,
phpdocumentor/type-resolver  D version: 1.6.0, O version: 1.x-dev,
phpspec/prophecy  D version: v1.15.0, O version: v1.10.3,
phpunit/php-code-coverage  D version: 9.2.15, O version: 5.3.2,
phpunit/php-file-iterator  D version: 3.0.6, O version: 1.4.x-dev,
phpunit/php-text-template  D version: 2.0.4, O version: 1.2.1,
phpunit/php-timer  D version: 5.0.3, O version: 1.0.x-dev,
phpunit/phpunit  D version: 9.5.19, O version: 6.5.14,
psr/http-client  D version: 1.0.1, O version: dev-master,
psr/http-factory  D version: 1.0.1, O version: dev-master,
psr/log  D version: 1.1.4, O version: dev-master,
sebastian/code-unit-reverse-lookup  D version: 2.0.3, O version: 1.0.x-dev,
sebastian/comparator  D version: 4.0.6, O version: 2.1.3,
sebastian/diff  D version: 4.0.4, O version: 2.0.x-dev,
sebastian/environment  D version: 5.1.3, O version: 3.1.0,
sebastian/exporter  D version: 4.0.4, O version: 3.1.x-dev,
sebastian/global-state  D version: 5.0.5, O version: 2.0.0,
sebastian/object-enumerator  D version: 4.0.4, O version: 3.0.x-dev,
sebastian/object-reflector  D version: 2.0.4, O version: 1.1.x-dev,
sebastian/recursion-context  D version: 4.0.4, O version: 3.0.x-dev,
sebastian/resource-operations  D version: 3.0.3, O version: 1.0.0,
sebastian/version  D version: 3.0.2, O version: 2.0.1,
symfony/http-foundation  D version: v4.4.34, O version: 4.4.x-dev,
symfony/mime  D version: v5.4.0, O version: 4.4.x-dev,
symfony/polyfill-ctype  D version: v1.23.0, O version: dev-main,
symfony/polyfill-intl-idn  D version: v1.23.0, O version: dev-main,
symfony/polyfill-intl-normalizer  D version: v1.23.0, O version: dev-main,
symfony/polyfill-mbstring  D version: v1.23.1, O version: dev-main,
symfony/polyfill-php72  D version: v1.25.0, O version: dev-main,
symfony/polyfill-php80  D version: v1.23.1, O version: dev-main,
theseer/tokenizer  D version: 1.2.1, O version: 1.2.0,
webmozart/assert  D version: 1.10.0, O version: dev-master,
`

**Comment by eileenmcnaughton** [comment]
@stesi561 I mentioned this on chat too but geocoder uses `composer replace` in the json to not add some packages

**Comment by stesi561** [comment]
Nice - looks like it works if you have a conflict with a CiviCRM package - but that won't work with a conflict with a Drupal D9 one as no guarantee it's available on WP/D7/Joomla. I think in this case perhaps better to strip out vendor from the extension dir and merge into the Drupal Vendor directory.

**Comment by eileenmcnaughton** [comment]
@stesi561 at wmf we require the merge plugin in composer
        "wikimedia/composer-merge-plugin": "^2",

And also in our composer.json we have this config (at the same level as 'require' , 'repositories'  etc)

    "extra": {
      "merge-plugin": {
        "include": [
          "drupal/sites/default/civicrm/extensions/*/composer.json"
        ],
        "recurse": true,
        "replace": false,
        "ignore-duplicates": false,
        "merge-dev": true,
        "merge-extra": false,
        "merge-extra-deep": false,
        "merge-scripts": false
      }
    },
