### ISSUE TITLE
Show user friendly description message on the payment screen

### ISSUE THREAD

**Issue by kurund** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#232]
I have tested this for SagePay

## Current
Order description: 14806214-4919138-Fundrai

## Suggested
Order description: Online Contribution: Fundraiser

**Comment by eileenmcnaughton** [comment]
I think I merged this too quickly - the message is better for end users - but not much use for admins logged into the (eg.) Sage console looking at a list of payments
