### ISSUE TITLE
Failed or cancelled payment still leads to positive Thank You page

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#25]
With our Mollie implementation everything works ok with the master code as of februari 15th :-)

Only thing is that an unsuccessful payment still leads to positive feedback (see screenshot)
`Thank you for your support. Your contribution will help us build even better tools.`

I am not sure if that is a Mollie thing or applies to more Omnipay payment providers.

Screenshot of display after **canceling** the payment:
![screenshot from 2017-02-15 13-20-00](https://cloud.githubusercontent.com/assets/2195908/22974296/f9834fc6-f381-11e6-867e-4bfe770d1c65.png)

Is this a Mollie issue, an Omnipay issue, or a core issue?

**Comment by eileenmcnaughton** [comment]
Well it's kind of a mix - I'm struggling with Mollie being so stubborn & not passing back ANY info in the url. I guess I could try in the return url appending the contribution id to the return url

**Comment by magnolia61** [comment]
I found some info on how Mollie handles failed & canceled statuses. See: https://github.com/mollie/mollie-api-php/issues/18 
Mollie does not work with a separate CancelURL but does send the statusinfo back to be handled:
```

"When a customer returns to your website (when the customer clicked "Back to the website"), your webhook gets called to inform your system that the customer has aborted the transaction.
In your webhook (or this example) you can specify what should happen when this happens"
```

if ($payment->isPaid() == TRUE)
{
    /**
     * At this point you'd probably want to start the process of
     * delivering the product to the customer.
     */
}
elseif ($payment->isOpen() == FALSE)
{
    /**
     * The payment isn't paid and isn't open anymore.
     * We can assume it was aborted.
     */
}

Ricardo,
Mollie

**Comment by eileenmcnaughton** [comment]
yes - the problem is Mollie does not put the transaction id in the url - the point of that last commit was to add it in a fairly acceptable way - ie https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/31f0051b8212fd71edddb0186c5a72955499c4d4#diff-840c05b0d81fc424f6c2f02dc3f9b914R187 adds it to the url before the processor id (4.6 +, but I'll be droppimg pre 4.7 support soon)

**Comment by magnolia61** [comment]
It does send the ID as a parameter

Found this info from the Mollie Webhook documentation:

"The webhook will be called with a single POST-parameter named id which for instance will contain the value tr_d0b0E3EA3v. You should use that id to actively fetch the payment to find out about it's status."

So probably we have to check for isOpen and isPaid proactively when the webhook us called by Mollie.

**Comment by eileenmcnaughton** [comment]
does the return url for the browser look like civicrm/paymen/ipn/{contributionID}/{paymentProcessorID} ?

**Comment by veelineen** [comment]
no it doesn't, see screenshot for the URL, on my system it's the same as in the screenshot.
It's something like:

https://weburl/?page=CiviCRM&q=civicrm/event/register&_qf_ThankYou_display=1&qfKey=the-key

@magnolia61 you're on WordPress/Civicrm as well? What did you set as webhook URL in the (old) Mollie interface (can't find it within the new Mollie interface).

**Comment by eileenmcnaughton** [comment]
it actually goes to one url & then redirects - so that url above seems like the second - not the one I was wanting to check

**Comment by veelineen** [comment]
there are probably three URL's nvolved in canceling. 
The first one is behind the cancel button. This one is:
https://www.mollie.com/paymentscreen/ideal/cancel-select-issuer/{some-token-seems-the-payment-id}?_formtoken={some-token}
This one seems to redirect the user to the redirect URL, which is the one I mentioned (this URL is mentioned in my Mollie log):
https://website/?page=CiviCRM&q=civicrm/event/register&_qf_ThankYou_display=1&qfKey={the-key}

Within the logs there's also a webhook URL for the payment. Mollie uses the webhook for status changes:
https://website/?page=CiviCRM&amp;q=civicrm/payment/ipn/{ipn}&amp;

**Comment by eileenmcnaughton** [comment]
so, on the latest code they should go to 
https://website/?page=CiviCRM&amp;q=civicrm/payment/ipn/{ipn}&

but be redirected (without noticing) to 
https://website/?page=CiviCRM&q=civicrm/event/register&_qf_ThankYou_display=1&qfKey={the-key}

**Comment by eileenmcnaughton** [comment]
Acutally
https://website/?page=CiviCRM&amp;q=civicrm/payment/ipn/{contributionID}/{ipn}&

**Comment by veelineen** [comment]
I tried with the latest code, but url's are like what I previously mentioned

**Comment by eileenmcnaughton** [comment]
I just tried this out and if the webhook has not yet done the update then it will need to go to that page as we don't know. However, if the contribution has already failed it should go to the failed url.

Note that the commit just prior to this one removed support for legacy civi versions so you need to be trying this on 4.7

**Comment by magnolia61** [comment]
https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/30 seems to solve this issue partially. I say partially because there is no notice onscreen about the failure, but the user is redirected to the payment screen (to maybe attempt another try, or another payment processor). I think this is the wanted behavior but a small message onscreen that the payment failed would probably be nice.

**Comment by eileenmcnaughton** [comment]
I added a commit with a message (in master, not released version)
