### ISSUE TITLE
WIP Transaction IDs are likely to be duplicated, leading to rejections

### ISSUE THREAD

**Issue by xurizaemon** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#26]
The existing method for generating transaction IDs will eventually fail on payment processors which require unique TxnId (DPS at least).

There are several ways this may be triggered, eg:

* Repeated transaction attempts for the same contribution.
* Multiple payments on a single contribution.
* A merchant account which generates sequential TxnIds from both CiviCRM and some other external sales system (eg clash with Ubercart generating order 123 and CiviCRM contribution 123).
* A merchant account used on multiple CiviCRM sites with sequential contribution IDs.
* Case where no contribution ID is available when the transaction ID is generated will fail eventually (`rand(0, 1000)` means transactions may fail more and more frequently as the "unique" space fills).

Cause may not be obvious to donors or sites and the failures may appear intermittent, as the message displayed to users is not clear and I don't think there's any way to push the failure(s) back to the site admin. 

Here's what the user sees if a TxnID is not unique with PaymentExpress PxPay:

![image](https://cloud.githubusercontent.com/assets/105608/25559514/d824a738-2d8f-11e7-9414-7c2c157b922d.png)

**Comment by eileenmcnaughton** [comment]
That is a shit DPS feature - although really only relevant to our dev account -and I'd rather keep the contribution ids as a general rule as they are meaningful 

However, Civi does have a setting for an invoice prefix - I'd rather prepend that than append a random number

**Comment by xurizaemon** [comment]
According to http://stackoverflow.com/a/20893746/43034 this behaviour is not unique to DPS (SagePay there). Even if it was, we can't pull random unique numbers from a pool of 1000 for long, and there are plenty of ways to end up with conflicting IDs.

This fix is not complete yet though, as the transaction ID is used interchangeably with contribution IDs elsewhere (eg IPN URL uses transaction ID but rejects non-integer values).

Best would be to separate the usage; for now I'm going to amend my PR to make "unique-ish" strings which happen to be integers until I have scope to tackle it further.

**Comment by eileenmcnaughton** [comment]
I don't mind getting rid of the rand - it's this part I don't like

$this->transaction_id = $contribution_id . '-' . uniqid();

Hopefully the other part would only ever apply to pre-4.7 sites anyway

**Comment by xurizaemon** [comment]
Can I get you to consider "several ways this may be triggered" from the initial bug report above?

It needs to be unique per merchant account (for processors with that requirement).

Agree that the line above won't work without wider changes to handle a unique transaction ID rather than a contribution ID.

**Comment by xurizaemon** [comment]
Seems this has affected some live sites as well. The PR here is not a complete fix yet. To check if a site has been affected, try this query -

    select * from civicrm_system_log where message like 'failed processor transaction%';

then check the "context" field for messages about duplicate transaction IDs (for DPS, this says _TxnId/TxnRef duplicate_ but for other processors the message will likely differ).

**Comment by eileenmcnaughton** [comment]
My preference is still to optionally use the invoice prefix configured for the site. If a site needs something more complex they can use the hook I think

**Comment by petednz** [comment]
not sure if this filtered back up here, but i 'think' the issue we were hitting was lots of testing with live details on a test site, then we moved over to live site, and the Contrib IDs that were being pushed out were IDs that had already been sent out from the dev site. Not sure if that makes sense, but we opted to jump our ID value in contrib table up by a thousand to avoid further issues if that was in fact the issue

**Comment by eileenmcnaughton** [comment]
yep - that sounds like the issue

**Comment by petednz** [comment]
is this something that jitendra could tackle?

**Comment by eileenmcnaughton** [comment]
So, there are 2 parts to this -
1) there should always be a contribution id in versions 4.7+ - I think this might NOT be the case in webform :-( & there is a ticket on event to handle. If not present I don't care what the number is..... I would focus on fixing the missing number - but the hack in the else would get it working in the iterim
2) prepend the site-specific invoice prefix to the processor. It might make sense to actually add a field to the payment_processor table in core & have a per-processor prefix? Or if not in core use the entity_setting extension

**Comment by xurizaemon** [comment]
Just want to re-state something I mentioned above in case it didn't come through: This does **NOT** only affect dev sites. It has affected two production sites; on one of those the cause appears to have been testing on a dev site that existed in parallel. (See internal ticket 12419 for specifics.)

If the workaround is "don't ever test on dev sites", or "every time you test on a dev site you need to run the MySQL command from [this comment](https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/issues/26#issuecomment-299096238)", then that may need to be documented. IMO that's insufficient, but the underlying conflation in Omnipay of contribution ID (sequential) and transaction ID (unique, potential for multiple per contribution) means this isn't as quick a fix as I hoped.

Omnipay users ought to be able to test a transaction from a dev instance without it breaking transactions on their live site, but that's not the only way this bug can affect a site.

> there should always be a contribution id in versions 4.7+ - I think this might NOT be the case in webform :-( & there is a ticket on event to handle. If not present I don't care what the number is..... I would focus on fixing the missing number - but the hack in the else would get it working in the iterim

There *is* a contribution ID. It's the fact that this is identical for multiple transactions that's the problem?

> prepend the site-specific invoice prefix to the processor. It might make sense to actually add a field to the payment_processor table in core & have a per-processor prefix? Or if not in core use the entity_setting extension

Currently IPN will fail if the transaction ID is not an integer (which matches the contribution at hand), so unless the prefix is numeric (which only smooshes around the chance of conflict) I don't see how this will help.

**Comment by eileenmcnaughton** [comment]
OK - then - so we should fix this 'Currently IPN will fail if the transaction ID is not an integer '

**Comment by eileenmcnaughton** [comment]
Is that just the bit in the Omnipay handlePayment that is requiring that?

**Comment by xurizaemon** [comment]
Try it. I gave as much detail as I thought would be helpful above.

We fail hard if the contribution is not an integer (CRM_Utils_Check or whatever it is), easy to test out. We also use txnid and contrib ID interchangeably in more than one place. There's work to do to separate them.

It's not impossible, but it seems to require bigger steps than the approaches I explored (see #27). Which is why I'm hoping to get you to see the issue at hand and "buy in" to a fix.

**Comment by eileenmcnaughton** [comment]
The transaction id is unpacked here 

https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/blob/master/CRM/Core/Payment/OmnipayMultiProcessor.php#L683

I would think that if a predictable string were prepended then at that point it could be predictably stripped

**Comment by eileenmcnaughton** [comment]
From April onwards it will be possible (although not UI-easy) to configure a prefix on a per-processor basis to be prepended to the transaction string https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/971253ba29d4fa21372142cb3fb11122639b4640

**Comment by petednz** [comment]
@jitendrapurohit can you pls digest/remember this info in case it helps us with yf so we can run contributions from dev and live site without chewing up the contrib ids

**Comment by eileenmcnaughton** [comment]
closing per comments on Feb - will at some point make easier in the UI
