### ISSUE TITLE
New URLs for Sage Pay / Opayo

### ISSUE THREAD

**Issue by wmortada** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#263]
Elavon, who now own Sage Pay (now called Opayo)  have updated the endpoint URLs.

Email from Opayo:

> Following the updates earlier this year with the Opayo gateway becoming a payment product under the Elavon brand; we wanted to let you know about further exciting changes.  
> 
> Opayo has been a key member of the Elavon family for over three years now, and as we continue with the integration into Elavon we will soon make updates to the URLs you use for your transactions and reporting.
> 
> What does this mean?
> 
> The URLs you use to send transactions to Opayo will be changing to an Elavon domain and you need to make the changes to send your transactions to the updated URLs. 
> 
> These changes must be made by **31st March 2024**, this is when the SagePay URLs will cease to work.

The latest version of `omnipay-sagepay` (v4.1.1) incorporates [these changes](https://github.com/thephpleague/omnipay-sagepay/pull/193) but this extension appears to use an older version (v3.2.3) which uses the old URLs.

Could the `omnipay-sagepay` library be updated to the latest version?

**Comment by eileenmcnaughton** [comment]
I think this is resolved with ^^

**Comment by wmortada** [comment]
Thanks @eileenmcnaughton, that PR is closed but presume you mean: https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/9d47680930c699af8d179a6e048430b2463ff551 and https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/4b6101977249d49e7c35436e516175f2cd414ff9 

I'll give it a test.

**Comment by wmortada** [comment]
We've deployed `master` and tested on a client site. This appears to be working fine and uses the new URLs.

Thanks @eileenmcnaughton. I'll close this issue now.

**Comment by pradpnayak** [comment]
We have cloned the master and tested it. The payments work fine with the new endpoint. 

Soon there will be a newer version available under extensions listings?

**Comment by wmortada** [comment]
It turns out that I wasn't testing a clean copy of `master`. When I did, we realised that there were some missing files as per #266.

**Comment by eileenmcnaughton** [comment]
I just did a new composer install --no-dev

**Comment by wmortada** [comment]
Thanks @eileenmcnaughton. I've re-run the tests with the latest `master` and this is working fine now. I think this is ready for a release.

**Comment by eileenmcnaughton** [comment]
OK @wmortada done

**Comment by wmortada** [comment]
Thanks @eileenmcnaughton
