### ISSUE TITLE
Current master is broken due to missing vendor files

### ISSUE THREAD

**Issue by kurund** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#266]
@eileenmcnaughton 

I think problem might be with this commit: https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/66f14eb13400999636d864efcd7f9761d88c5ad9

We are ignoring below vendors in `.gitignore`:
 - vendor/myclabs
 - vendor/mockery
 - vendor/phpunit

However, auto-loading files expecting them to be part of the repo. For eg in `autoload_files.php`  line 15.

**Comment by eileenmcnaughton** [comment]
@kurund I just re-ran with no-dev - I guess the .gitignore is doing more harm than good

**Comment by kurund** [comment]
@eileenmcnaughton 

Thank you for the quick response.

Now the master is back to normal and working as expected.

**Comment by eileenmcnaughton** [comment]
:-)
