### ISSUE TITLE
Unknown processor error omnipay_SagePay_Server

### ISSUE THREAD

**Issue by kurund** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#269]
We are getting below error when using SagePay
Error in logs:

```bash
[error] unknown processor error omnipay_SagePay_Server
Array
(
    [0] => Amount precision is too high for currency.
)
```

CiviCRM 5.69.5 ESR
Omnipay 3.23

**Comment by kurund** [comment]
CiviCRM is submitting the amount value as below
 
```bash
[amount] => 38.004
```

We are using price sets.

**Comment by kurund** [comment]
I have proposed a fix to CiviCRM Core: https://github.com/civicrm/civicrm-core/pull/30277

Closing this issue.

**Comment by kurund** [comment]
This is fixed in https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/122be23065cc050bf586f9a4720d3c29cf7ab413

**Comment by kurund** [comment]
@eileenmcnaughton 

Looks like the release is not available on c.o.  May be it's because of  `3,24` instead `3.24`

**Comment by eileenmcnaughton** [comment]
you are all so fussy.... should be fixed

**Comment by wmortada** [comment]
Thanks @eileenmcnaughton. It's there now.

**Comment by wmortada** [comment]
@kurund we can close this now.
