### ISSUE TITLE
Record transaction failures via CiviCRM log

### ISSUE THREAD

**Issue by xurizaemon** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#28]
Currently, failed transactions (eg those from #26) are not reported to CiviCRM debug log.

This may reduce the likelihood of sites realising that transaction failures are occurring.

Recording failures to CiviCRM debug log may better support sites discovering such issues.

**Comment by eileenmcnaughton** [comment]
seems like we merged a fix on this
