### ISSUE TITLE
Usage of completePurchase

### ISSUE THREAD

**Issue by sergej-koscejev** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#3]
I've been continuing the work on implementing my Omnipay gateway to use in conjunction with your multiprocessor, and I've stumbled upon what I think is a potential problem.

The code uses completePurchase() to process payment notifications, but the Omnipay design is AFAICT to use this method for outgoing calls, as evidenced by the fact that it should accept the same parameters as purchase(). According to thephpleague/omnipay#83 it was considered to have some other method like notify() on gateways that support incoming notifications but apparently it hasn't yet been implemented.

So I propose the code to be changed to look for a "notify" method on the gateway, and call that one instead of completePurchase, if found (and throw an error if it wasn't found). And if this works well, we could contribute the method support to omnipay (which would mean just describing its contract).

**Comment by eileenmcnaughton** [comment]
I'm closing this - since you did a PR for GoPay I assume you got it working

**Comment by sergej-koscejev** [comment]
Haven't got it confirmed from the client still, but I agree, the issue can be closed for now.
