### ISSUE TITLE
README & docs

### ISSUE THREAD

**Issue by xurizaemon** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#31]
Making the README pretty, documenting some config.

**Comment by eileenmcnaughton** [comment]
Is this covered by the PR? I find on github the whole PR vs issue thing confusing - ie. do we need both? Or should we only open an issue when there is no PR since we'll probably forget to close it after PR review ....

**Comment by xurizaemon** [comment]
Fair enough. Yeah I think (from the ID increments) that they are the same thing in different outfits.
