### ISSUE TITLE
API error: 'payment_type' is not a valid option for field option_group_id

### ISSUE THREAD

**Issue by deputt** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#38]
I received the following error upon installing the extension:
- API error: 'payment_type' is not a valid option for field option_group_id
As such, the extension was downloaded and enabled but no options available.
I'm using Joomla 3.8.1 with CiviCRM 4.7.25.

**Comment by eileenmcnaughton** [comment]
That should be created on install - try running the system.flush api from the api explorer

**Comment by deputt** [comment]
After running system.flush, I got the following message:


   1. {
       "trace":"
   #0 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(292):
CRM_Core_ManagedEntities->onApiError('option_value', 'create', Array,
Array)\n
   #1 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(196):
CRM_Core_ManagedEntities->disableEntity(Object(CRM_Core_DAO_Managed))\n
   #2 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(123):
CRM_Core_ManagedEntities->reconcileDisabledModules()\n
   #3 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(395):
CRM_Core_ManagedEntities->reconcile()\n
   #4 /home/public_html/administrator/components/com_civicrm/civicrm/api/v3/System.php(50):
CRM_Core_Invoke::rebuildMenuAndCaches(false, false)\n
   #5 /home/public_html/administrator/components/com_civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89):
civicrm_api3_system_flush(Array)\n
   #6 /home/public_html/administrator/components/com_civicrm/civicrm/Civi/API/Kernel.php(169):
Civi\\API\\Provider\\MagicFunctionProvider->invoke(Array)\n
   #7 /home/public_html/administrator/components/com_civicrm/civicrm/Civi/API/Kernel.php(100):
Civi\\API\\Kernel->runRequest(Array)\n
   #8 /home/public_html/administrator/components/com_civicrm/civicrm/api/api.php(23):
Civi\\API\\Kernel->runSafe('System', 'flush', Array, NULL)\n
   #9 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Utils/REST.php(404):
civicrm_api('System', 'flush', Array)\n
   #10 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Utils/REST.php(641):
CRM_Utils_REST::process(Array, Array)\n
   #11 [internal function]: CRM_Utils_REST::ajax()\n
   #12 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(275):
call_user_func(Array)\n
   #13 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(84):
CRM_Core_Invoke::runItem(Array)\n
   #14 /home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(52):
CRM_Core_Invoke::_invoke(Array)\n
   #15 /home/public_html/administrator/components/com_civicrm/civicrm.php(121):
CRM_Core_Invoke::invoke(Array)\n
   #16 /home/public_html/administrator/components/com_civicrm/civicrm.php(40):
civicrm_invoke()\n
   #17 /home/public_html/libraries/src/Component/ComponentHelper.php(392):
require_once('/home/...')\n
   #18 /home/public_html/libraries/src/Component/ComponentHelper.php(367):
Joomla\\CMS\\Component\\ComponentHelper::executeComponent('/home/...')\n
   #19 /home/public_html/libraries/src/Application/AdministratorApplication.php(101):
Joomla\\CMS\\Component\\ComponentHelper::renderComponent('com_civicrm')\n
   #20 /home/public_html/libraries/src/Application/AdministratorApplication.php(159):
Joomla\\CMS\\Application\\AdministratorApplication->dispatch()\n
   #21 /home/public_html/libraries/src/Application/CMSApplication.php(267):
Joomla\\CMS\\Application\\AdministratorApplication->doExecute()\n
   #22 /home/public_html/administrator/index.php(51):
Joomla\\CMS\\Application\\CMSApplication->execute()\n
   #23 {main}",
       "is_error": 1,
       "error_message": "API error: A fatal error was triggered"
   }

**Comment by eileenmcnaughton** [comment]
It seems to be trying to create them in the wrong order for some reason?

Check civicrm_option_group - you want to have a row like 
          'title' => 'Payment Type',
          'name' => 'payment_type',
          'description' => 'Payment Processor Payment type (configured on processor)',
          'is_reserved' => TRUE,
          'is_active' => TRUE,

And a row in civicrm_managed pointing to it like

`module`, `name`, `entity_type`, `entity_id`, `cleanup`
'nz.co.fuzion.omnipaymultiprocessor', 'payment_type', 'option_group', #option group id from above, NULL);

**Comment by deputt** [comment]
Thank you, Eileen, for your prompt reply.

Both items were missing from the database.

I added them manually via phpmyadmin as follows - screenshots after insert:


​
*I added the "String" data_type (above) after the error message below, but
still received the same message.*


​
I then enabled the extension and received the following message:

{

    "trace": "
#0
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(265):
CRM_Core_ManagedEntities->onApiError('option_value', 'create', Array,
Array)\n
#1
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(168):
CRM_Core_ManagedEntities->updateExistingEntity(Object(CRM_Core_DAO_Managed),
Array)\n
#2
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(141):
CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module),
Array)\n
#3
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/ManagedEntities.php(122):
CRM_Core_ManagedEntities->reconcileEnabledModules()\n
#4
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(395):
CRM_Core_ManagedEntities->reconcile()\n
#5
/home/public_html/administrator/components/com_civicrm/civicrm/api/v3/System.php(50):
CRM_Core_Invoke::rebuildMenuAndCaches(false, false)\n
#6
/home/public_html/administrator/components/com_civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89):
civicrm_api3_system_flush(Array)\n
#7
/home/public_html/administrator/components/com_civicrm/civicrm/Civi/API/Kernel.php(169):
Civi\\API\\Provider\\MagicFunctionProvider->invoke(Array)\n
#8
/home/public_html/administrator/components/com_civicrm/civicrm/Civi/API/Kernel.php(100):
Civi\\API\\Kernel->runRequest(Array)\n
#9
/home/public_html/administrator/components/com_civicrm/civicrm/api/api.php(23):
Civi\\API\\Kernel->runSafe('System', 'flush', Array, NULL)\n
#10
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Utils/REST.php(404):
civicrm_api('System', 'flush', Array)\n
#11
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Utils/REST.php(641):
CRM_Utils_REST::process(Array, Array)\n
#12 [internal function]: CRM_Utils_REST::ajax()\n
#13
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(275):
call_user_func(Array)\n
#14
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(84):
CRM_Core_Invoke::runItem(Array)\n
#15
/home/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(52):
CRM_Core_Invoke::_invoke(Array)\n
#16
/home/public_html/administrator/components/com_civicrm/civicrm.php(121):
CRM_Core_Invoke::invoke(Array)\n
#17 /home/public_html/administrator/components/com_civicrm/civicrm.php(40):
civicrm_invoke()\n
#18 /home/public_html/libraries/src/Component/ComponentHelper.php(392):
require_once('/home/...')\n
#19 /home/public_html/libraries/src/Component/ComponentHelper.php(367):
Joomla\\CMS\\Component\\ComponentHelper::executeComponent('/home/...')\n
#20
/home/public_html/libraries/src/Application/AdministratorApplication.php(101):
Joomla\\CMS\\Component\\ComponentHelper::renderComponent('com_civicrm')\n
#21
/home/public_html/libraries/src/Application/AdministratorApplication.php(159):
Joomla\\CMS\\Application\\AdministratorApplication->dispatch()\n
#22 /home/public_html/libraries/src/Application/CMSApplication.php(267):
Joomla\\CMS\\Application\\AdministratorApplication->doExecute()\n
#23 /home/public_html/administrator/index.php(51):
Joomla\\CMS\\Application\\CMSApplication->execute()\n
#24 {main}",
    "is_error": 1,
    "error_message": "API error: A fatal error was triggered:  is not of
type String"
}

On Mon, Oct 16, 2017 at 8:27 AM, Eileen McNaughton <notifications@github.com

**Comment by eileenmcnaughton** [comment]
I can't see the screenshots - here are the entitie's it's trying to create

https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/blob/master/Metadata/optiongroup.mgd.php

You could just muscle through with phpmyadmin if you want. Once if finds a row in civicrm_managed for each entity it will stop trying. (I have always intended this setting to go into core eventually)

**Comment by deputt** [comment]
Woohoo! Thanks, Eileen! I managed to manually insert the 3 missing records
into civicrm_option_value, and could add Omnipay processors.

Now to try adding iPay88 processor to the list...

pc3

On Mon, Oct 16, 2017 at 9:11 AM, Eileen McNaughton <notifications@github.com
