### ISSUE TITLE
Payment methods are gone after upgrade civi+omnipay

### ISSUE THREAD

**Issue by stijndmd** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#40]
Hi all

Upgraded civicrm to 4.7.28 and omnipay to 2.4.

On my contributions page, the listed payment options are now gone. On the live website (with the old civi and omnipay), the payment options are still listed.

Thoughts?

**Comment by eileenmcnaughton** [comment]
By payment options I assume you mean payment processors? Are they still available & selected on the contribution page configuration page? Which processors are you using

**Comment by stijndmd** [comment]
They are no longer shown/available on the contribution confirmation page.

We're using the Mollie payment and bank transfer. But it's just the options that aren't showing anymore for the users. There are no javascript errors in the console that aren't also there on the live website.

**Comment by stijndmd** [comment]
The entire <fieldset> element in the screenshot below is missing on the upgraded version of this website.

![screen shot 2017-12-18 at 16 06 34](https://user-images.githubusercontent.com/2393272/34112685-a7fa3bd8-e40d-11e7-979e-b5aac91eb1b8.png)


Below is what I'm getting on the same page on the upgraded version. But I'm getting the same thing when I rewind the omnipay upgrade, so I'm thinking its something related to the civicrm upgrade.

<img width="870" alt="screen shot 2017-12-18 at 16 09 43" src="https://user-images.githubusercontent.com/2393272/34112779-ef88c3f2-e40d-11e7-9a48-39635aa543e9.png">

**Comment by eileenmcnaughton** [comment]
There were some regressions in 4.7.28 that affected sites using a point as a thousand separator  - https://github.com/civicrm/civicrm-core/pull/11412 and I'm wondering if the js that determines whether there is a monetary amount involved is maybe tripping up? Is there a js error?

**Comment by eileenmcnaughton** [comment]
It would be good if you join chat.civicrm.org to discuss / track this one down

**Comment by stijndmd** [comment]
Hi Eileen

Sorry for the huge delay here. The patch in the linked issue did not resolve my issue.
There are no useable js errors in console. (The same as the production environment which isn't updated yet and has working payment options).

I'll check to join the chat this afternoon if I don't find the problem before that.

**Comment by eileenmcnaughton** [comment]
SO it seems this section is missing ?
```
  {if $form.payment_processor_id.label}
  {* PP selection only works with JS enabled, so we hide it initially *}
  <fieldset class="crm-public-form-item crm-group payment_options-group" style="display:none;">
    <legend>{ts}Payment Options{/ts}</legend>
    <div class="crm-public-form-item crm-section payment_processor-section">
      <div class="label">{$form.payment_processor_id.label}</div>
      <div class="content">{$form.payment_processor_id.html}</div>
      <div class="clear"></div>
    </div>
  </fieldset>
  {/if}
```

**Comment by stijndmd** [comment]
Correct.

**Comment by stijndmd** [comment]
The problems were some legacy custom made extensions for events and contributions and are now fixed.

Thanks for the assistance though!

**Comment by eileenmcnaughton** [comment]
whoppee!
