### ISSUE TITLE
Security update for Symfony HttpKernel & HttpFoundation

### ISSUE THREAD

**Issue by wannesderoy** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#54]
Symfony (and Zend also) released security updates for its HttpKernel & HttpFoundation classes. The http-foundation is used in the omnipaymultiprocessor extension.See the releases here:
https://symfony.com/blog/symfony-3-3-18-released
https://framework.zend.com/security/advisory/ZF2018-01
Can the vendor package be updated?

**Comment by eileenmcnaughton** [comment]
Done & I issued a release https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/releases/tag/2.5
