### ISSUE TITLE
Performance loss when using Omnipay Multi Processor Payment Processor

### ISSUE THREAD

**Issue by kewljuice** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#56]
After performance testing on a Drupal8 & CiviCRM 5.4 website, we noticed that pages where the omnipaymultiprocessor is used, the loading time is considerably higher.

After commenting all code in the "_omnipaymultiprocessor_civix_civicrm_managed" function, these pages load 1/3 faster.

If I understand correctly, this function is necessary during enabling, disabling, and uninstalling the module. But I do not think we need this feature when loading contribution or event pages with online payment activated.

**Comment by eileenmcnaughton** [comment]
Thanks for the patch
