### ISSUE TITLE
Failure when calling Deprecated function CRM_Core_Payment_OmnipayMultiProcessor::doTransferCheckout

### ISSUE THREAD

**Issue by stesi561** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#83]
Using Drupal, webform_civicrm 4.26 and omnipaymultiprocessor 2.5 

On a basic webform - minimal fields submitting a contribution resulted in the following error: 

CRM_Core_Exception: Payment redirect failed in CRM_Core_Payment_OmnipayMultiProcessor->doTransferCheckout() (line 487 of sites/default/civicrm/extensions/nz.co.fuzion.omnipaymultiprocessor/CRM/Core/Payment/OmnipayMultiProcessor.php).

To resolve this problem I switched the call in webform from the deprecated doTransferCheckout to the recommended doPayment.  Webform 4.26 currently has a test that checks for existence of doTransferCheckout then falls back to doPayment (this should probably be reversed) but the function could also possibly be removed from this extension? In #35 it looks like it was attempted to remove this function but was required by webform. Now that webform is checking for the existence of this function before falling back to doPayment perhaps removal of it could proceed in a future version? The fix is present in webform_civicrm 4.19+

**Comment by eileenmcnaughton** [comment]
@stesi561 so you are saying the released webform version is better without doTransferPayment? I'm happy for it to be removed if you want to do a PR

**Comment by stesi561** [comment]
I've not fully dug into what's happening. But if you remove doTransferPayment - you will cause errors with older versions of webform? However given the latest version of civi breaks older versions of webforms - the CRM_Core_Payment_Form::getCreditCardCSSNames() error. This would mean you would only be impacting people who are not taking credit card numbers on site? Not sure how big a pool that is?

**Comment by eileenmcnaughton** [comment]
I'm not worried about supporting older versions of webform with latest version of omnipay - people can use an older release of omnipay if they need to

**Comment by hoegrammer** [comment]
I've also come across this  issue and removing the whole doTransferPayment function helped.

**Comment by eileenmcnaughton** [comment]
I'm pretty sure it's actually gone from latest master branch

**Comment by eileenmcnaughton** [comment]
this seems to have aged out of relevance
