### ISSUE TITLE
omnipay with NMI

### ISSUE THREAD

**Issue by netzih** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#85]
Trying to add NMI integration to OMNIPAY.
I added 
            "{
            "type": "git",
            "url":  "https://github.com/nerdmedia/omnipay-nmi.git"
        }"
 and required "nerdmedia/omnipay-nmi":"^3.0@dev" to the composer file.

I also created a MGD.php file in the Metadata folder.
I used the MGD from Authorize AIM and just changed the details to
"[
    'name' => 'OmniPay - nmi',
    'entity' => 'payment_processor_type',
    'params' => array(
      'version' => 3,
      'title' => 'OmniPay - nmi',
      'name' => 'omnipay-nmi',"
      'description' => 'NMI (Network Merchants Inc.) driver for the Omnipay PHP payment processing library',"

It comes up as a processor to add in CIVICRM processors but when going to process any payments after putting in the cc details i'm getting Class '\Omnipay\omnipay-nmi\Gateway' not found.

What am I missing?

**Comment by netzih** [comment]
BTW I also tried putting "NMI_DirectPost" as the name (as in the readme but it did not help)

**Comment by mattwire** [comment]
@netzih Did you try "omnipay_nmi" as the name?

**Comment by netzih** [comment]
I did
Did not work

**Comment by eileenmcnaughton** [comment]
With this patch I was able to get the processor to load - https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/89 - obviously I couldn't test a transaction

**Comment by netzih** [comment]
I got the processor to load too before when testing a transaction I'm getting got error 
"Class '\Omnipay\nmi\Gateway' not found"
Now when I used the data in your patch I'm getting  "Class '\Omnipay\NMI\DirectPostGateway' not found" when putting through a transaction.
(I updated the composer.json and created the MGD file for NMI with the file you put in the latest commit [#89](https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/89)

**Comment by eileenmcnaughton** [comment]
did you run composer update? If you check out the branch I created you'll have the same code I was working with

**Comment by netzih** [comment]
Good point. I forgot.
Just ran composer. Seems like it worked.
Now I got "Payment Processor Error message :Sorry, there was an error processing your payment. Please try again later.Authentication Failed"
So that probably means the problem now is with my API keys.
Have to figure it out now with my payment processor.
Thanks.

**Comment by eileenmcnaughton** [comment]
Note that I guessed the required credential fields (username & password) based on a quick read of the NMI code - it might be that other credentials are needed & the mgd would need to be updated to reflect that

**Comment by netzih** [comment]
Great thanx so much.

**Comment by netzih** [comment]
This issue was probably with my NMI connection than with the extension so closing.
